server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_arqui
    username: postgres
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
