spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_arqui
    username: postgres
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: migueleduardofer10@gmail.com
    password: ehqpioomhjedhjco
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/
